### ISSUE TITLE
Working with home assistant 101.2?

### ISSUE THREAD

**Issue by neomvll** [iantrich/radial-menu#11]
Hi, today I update my home assistant from 100.2 to 101.2 and radial-menu is not working anymore.
When I click in any icon from radial-menu, I got "TypeError: Cannot read property 'hasDoubleClick' of undefined" on logs
Can you confirm please?

**Comment by iantrich** [comment]
I cannot, but a new release was just put out. Give that a try and be sure to clear your browser cache.

**Comment by neomvll** [comment]
New version is ok!
Thanks!
