### ISSUE TITLE
Horizontal menu option?

### ISSUE THREAD

**Issue by dannymertens** [iantrich/radial-menu#16]
**Is your feature request related to a problem? Please describe.**

The menu works great and I want to use it for my dashboard on a mobile, tablet, but there is just to much space that you loose now when the menu is collapsed

**Describe the solution you'd like**

Would be great if we can have an option to have all the menu items in a horizontal list and they collapse horizontal (left right) so that we can use this as a small dynamic menu bar in the dashboard

**Describe alternatives you've considered**

Button bar, paper buttons, but I like that your menu can collapse so we don't have to see the buttons all the time if not needed, more clean look and feel

**Additional context**

![image](https://user-images.githubusercontent.com/46963011/78449885-d6cbf580-767a-11ea-9b49-702742ba98d9.png)

![image](https://user-images.githubusercontent.com/46963011/78449889-df243080-767a-11ea-9e08-68a2e0fa2c77.png)

**Comment by iantrich** [comment]
Wouldn’t be very radial then

**Comment by dannymertens** [comment]
I know, so new card horizontal menu ;-) because would be very ice to be honest ;-)

Kind regards,
Met vriendelijke groet,

Danny Mertens
