### ISSUE TITLE
Haptic feedback on Android

### ISSUE THREAD

**Issue by goodlucknow** [iantrich/radial-menu#17]
**Checklist:**

- [x] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**
1.5.0

**Last working release (if known):**

**Browser and Operating System:**
Chrome on Android, Official HA app on Android

**Description of problem:**

Issue occurs in chrome and in the official HA app on Android, when tapping a menu item with tap_action set to toggle or call-service, the haptic feedback vibrates twice even though only a single tap is registered. 
Functions normally otherwise.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by iantrich** [comment]
You can set the haptic you wish manually. Check the docs
