### ISSUE TITLE
Feature Request: No hide radial menu when clicked + tap_action

### ISSUE THREAD

**Issue by neomvll** [iantrich/radial-menu#5]
First of all: Thanks for the great custom card, it is very useful!!

I have many radial menus and some is like a pad, to control my TV, Kodi etc.
Would be very useful if we have a feature to turn the radial menu fixed, without hide when tap the center button, and the center button have the tap_action option.
If we have a radial menu like below, the pad will be perfect:
...
always_show: true
tap_action:
 action: call-service
 service: switch.turn_on
 service_data:
 entity_id: switch.kodi_input_select

**Comment by iantrich** [comment]
You can accomplish part of this already by setting 

```yaml
default_open: true
default_dismiss: false
```

I like the idea of a tap action. I'll look into adding that

**Comment by neomvll** [comment]
> You can accomplish part of this already by setting
> 
> ```yaml
> default_open: true
> default_dismiss: false
> ```
> 
> I like the idea of a tap action. I'll look into adding that

Nice !
I'm using w/ open and no dismiss. Now, I only need the tap_action.
Tell me if you need a tester :)

**Comment by iantrich** [comment]
Too late, already released :)

Fixed in release v1.4.0
