### ISSUE TITLE
1.4.2 tap_action bug

### ISSUE THREAD

**Issue by neomvll** [iantrich/radial-menu#6]
Hi, just updated the code to 1.4.2 and the center tap_action is not working or I doing something wrong, but items is ok:

`- type: custom:radial-menu
icon: mdi:kodi
name: KODI
default_dismiss: false
default_open: true
entity: switch.kodi_input_up
tap_action:
  action: call-service
  service: switch.turn_off
  service_data:
	entity_id: switch.kodi_input_up
items:
  - name: Up
	icon: mdi:arrow-up-bold
	tap_action: 
	  action: call-service
	  service: switch.turn_off
	  service_data:
		entity_id: switch.kodi_input_up`

This feature will be better if we have a option for radial menu still showing even if center button is clicked. That is useful for a pad with a "ok center button" and `default_dismiss: false default_open: true` not keep radial open after the tap

**Comment by neomvll** [comment]
hi, after update to 1.4.3, tap action is working in pc :), but not in my tablet and phone. 
Chrome Version issue?
PC: 74.0.3729.131 
Phone: 73.0.3683.90
Tablet: 73.0.3683.90

Tablet FF and MIUI browser(phone) are working very well

**Comment by iantrich** [comment]
Possible cache issue. Try clearing cache on phone and tablet in chrome

**Comment by neomvll** [comment]
maybe, I'll try later and back to you

**Comment by neomvll** [comment]
> Possible cache issue. Try clearing cache on phone and tablet in chrome

cache cleaned, not working here, the only diference is the browser version :(

**Comment by neomvll** [comment]
Last browser update for tablet and phone fix it.
Ty!!
